### ISSUE TITLE
[TODO] XLM-Roberta-large 돌려보고 EM 상승하는지 확인

### ISSUE THREAD

**Issue by sooyounlee** [VumBleBot/Group-Activity#13]
## 📌  요약

- (수행 전) XLM-Roberta-large 돌려보고 EM 상승하는지 확인

- (수행 후) EM 6.25, F1 2.57 -> EM이 6.25인데 F1이 어떻게 2.57일 수 있나..?

### Before

- XLM-Roberta-large 돌려보고 EM 상승하는지 확인해서 코드가 잘 돌아가고 있는지 확인. 건모님이 돌린 결과 EM이 2.5%는 나오므로, 결과가 재현되는지 확인하고 안된다면 건모님과 setting 비교 예정

### After

- XML Roberta large 돌렸고, 3000 step 제출했는데 EM이 올라간걸 보면 XML roberta가 어느 정도 exact matching을 내 주는 것 같긴 함
- 그런데 F1이 저렇게 낮게 나올 수 있는건지 궁금함
- Sentencepiece 라이브러리를 inference 단에서 추가했는데 어느 정도 성능이 나오는게, 어떻게 training을 한 건지 궁금함

**Comment by sooyounlee** [comment]
Sentencepiece library를 설치 안해서 inference에서 오류가 났는데, 생각해보니 그럼 training도 제대로 되지 않았을 것 같아서 다른 모델들도 다시 확인해야할 수도 있을 듯
`pip install sentencepiece` 로 설치함

**Comment by olenmg** [comment]
> Sentencepiece library를 설치 안해서 inference에서 오류가 났는데, 생각해보니 그럼 training도 제대로 되지 않았을 것 같아서 다른 모델들도 다시 확인해야할 수도 있을 듯
> `pip install sentencepiece` 로 설치함

저도 xlm-roberta-base 돌릴 때 에러나서 sentencepiece 따로 설치했습니다! 그래도 EM은 0.0 이었네요 ㅜ.ㅜ

**Comment by sooyounlee** [comment]
> > Sentencepiece library를 설치 안해서 inference에서 오류가 났는데, 생각해보니 그럼 training도 제대로 되지 않았을 것 같아서 다른 모델들도 다시 확인해야할 수도 있을 듯
> > `pip install sentencepiece` 로 설치함
> 
> 저도 xlm-roberta-base 돌릴 때 에러나서 sentencepiece 따로 설치했습니다! 그래도 EM은 0.0 이었네요 ㅜ.ㅜ

저는 돌릴 때는 에러 안나다가 인퍼런스 할 때만 에러 나더라구요! large 모델이 답인가요..ㅋㅋㅋ

**Comment by olenmg** [comment]
엇 저는 train 단계에서부터 tokenizer가 old version이라고 뜨면서 안됐던거 같은데.. 여기도 뭔가 있나보네요
