### ISSUE TITLE
[TODO] huggingface document review

### ISSUE THREAD

**Issue by olenmg** [VumBleBot/Group-Activity#14]
## 📌  요약

- (수행 전) huggingface document 정독 이후 baseline code 분석

- (수행 후) 

### Before

- baseline code 보니 huggingface document와 어느정도 일치하는 부분이 있는 것 확인

- huggingface document에서 해당 부분 정독 이후 baseline code 분석

### After

-

**Comment by sooyounlee** [comment]
종헌님 이거 닫으면 될까요?
