### ISSUE TITLE
[QA/REVIEW] EM보다 F1이 낮을 수 있나요?

### ISSUE THREAD

**Issue by sooyounlee** [VumBleBot/Group-Activity#16]
## 🤔  궁금한 점

- XML_Roberta_large로 트레인 후 제출하니 EM이 F1보다 높게 나왔는데, 이게 가능한가요?

---

## 📚  레퍼런스 첨부

- EM과 F1 수식 보면서 이해하기

**Comment by olenmg** [comment]
헉.. 답이 짧은 것들 위주로 다 맞히고, 답이 긴 것들을 많이 틀렸으면 가능할 것 같긴한데 신기하네요ㅋㅋㅋㅋㅋ

**Comment by sooyounlee** [comment]
아...그래서 그런가봅니다... inference한 결과 보니 다 엄청 짧은 토큰들이더라구요.. 수식 좀 더 이해해봐야겠어요 ㅋㅋ
![image](https://user-images.githubusercontent.com/21062594/116247822-33c6ac00-a7a6-11eb-9aa7-496511c0fd9a.png)
