### ISSUE TITLE
[SUGGEST] RoBERTa 모델 추가

### ISSUE THREAD

**Issue by SeongIkKim** [VumBleBot/Group-Activity#3]
## ✔️  추가하고싶은 기능

- 프로젝트에 덧붙이고 싶은 기능들을 제안합니다. 아래의 종류에 맞게 체크해주세요.

- [ ] Data
- [ ] Preprocessing
- [x] Model
- [ ] Feature
- [ ] Paper
- [ ] Serving
- [ ] ETC (ex - library, reference)

==========
상세정보는 여기에 적어주세요.
==========

---

## 📚  레퍼런스 첨부

- 해당 기능에 대한 정보를 어디서 알게되었는지 출처를 기록해주세요!
- 책, 블로그, 유튜브, 논문 등

---
## 📸  스크린샷 

- 해당 기능을 적용시켰을 때의 사례를 미리볼 수 있게 사진 등으로 첨부해주세요.

**Comment by ggm1207** [comment]
넵!
