### ISSUE TITLE
[SUGGEST] 정답 Token이 UNK 토큰인 경우. 

### ISSUE THREAD

**Issue by ggm1207** [VumBleBot/Group-Activity#42]
## ✔️  추가하고싶은 기능

- 프로젝트에 덧붙이고 싶은 기능들을 제안합니다. 아래의 종류에 맞게 체크해주세요.

- [ ] Data
- [x] Preprocessing
- [ ] Model
- [ ] Feature
- [ ] Paper
- [ ] Serving
- [ ] ETC (ex - library, reference.

==========
정답 Token이 UNK 토큰인 경우 [unused**] 토큰 사용해서 vocab에 추가하기

- UNK 토큰은 미리 전처리를 수행함으로써 구할 수 있습니다. ( Model에 종속적 )
- add_vocab.txt 또는 add_vocab.py 같은 형태로 구현하여 학습 이전에 vocab 을 추가하는 기능 제안합니다!

> 전제 조건은 UNK 토큰이 있어야 합니다.

==========

---

## 📚  레퍼런스 첨부

- 해당 기능에 대한 정보를 어디서 알게되었는지 출처를 기록해주세요!
- 책, 블로그, 유튜브, 논문 등

---
## 📸  스크린샷 

- 해당 기능을 적용시켰을 때의 사례를 미리볼 수 있게 사진 등으로 첨부해주세요.

**Comment by olenmg** [comment]
그런데 이렇게 하면 전에는 못맞힐 정답을 이제는 맞힐 수 있게 될까요?
