### ISSUE TITLE
[TODO] DenseRetriever 성능 향상

### ISSUE THREAD

**Issue by ggm1207** [VumBleBot/Group-Activity#49]
## 📌  요약

- (수행 전) 하이퍼 파라미터 수정

- (수행 후) 결과는 어땠는지

### Before

- question PAD 길이 'longest'로 바꿔서 학습
- 새로 구현한 Negative Sampling된 데이터 셋으로 학습
- Train, Valid 데이터 셋 합쳐서 학습
- Train, Valid, KorQuad 데이터 셋 합쳐서 학습

### After

> 우선 Kobert 모델을 사용하면 안 된다. vocab_size가 다른 모델에 비해 턱없이 작다. 8002개 다른 모델들은 30000개 이상,

> KorQuad Fine Tuning한 모델을 사용 할 까 생각 중.. vocab_size가 11만개라서 정말 의미있는 단어들만 있는지 미심쩍기도 하지만 우선 사용. 일전에 acc가 0%로 수렴했는데 그 이유를 과대적합으로 보고 있다. 

- 01 question PAD 길이 'longest'로 바꿔서 학습
    - batch_size 16까지 가능해짐.
    - 
- 02 새로 구현한 Negative Sampling된 데이터 셋으로 학습
    - 코드 구조 좀 생각해 봐야 됨

- 03 Train, Valid 데이터 셋 합쳐서 학습
    - `kobert` 모델로 돌렸을 때 그렇게 큰 성능 향상은 없었다. validation이 240개 밖에 안 돼서 성능 차이가 크게 나는 것이 이상핟.  

- 04 Train, Valid, KorQuad 데이터 셋 합쳐서 학습

**Comment by ebbunnim** [comment]
참고 - [sentence-transformers](https://github.com/UKPLab/sentence-transformers)

**Comment by ebbunnim** [comment]
1. korquad 학습 -> train data 학습 
2. sampling 비율 조정
3. sentense transformers - multilinugal
