### ISSUE TITLE
[리뷰] question에 있는 단어가 context에서 얼마나 나타나는가?(EDA)

### ISSUE THREAD

**Issue by olenmg** [VumBleBot/Group-Activity#52]
## 📔  상세

질문에 포함된 단어가 context에서는 얼마나 나타나는지 확인해보는 작업을 해보았습니다.
의미있는 단어만 보기 위해 `mecab.pos`를 이용하여 아래 형태소들만 추출하여 비교하였습니다. 
- 체언: N*일반명사/고유명사/의존명사
- 접미사: XSN명사파생접미사 XPN체언접두사
- 한국어 외(영어, 한자, 숫자): SL영어 SH한자 SN숫자

![image](https://user-images.githubusercontent.com/61135159/117250991-ff767e00-ae7e-11eb-93a2-5ada282a1c52.png)
**겹치는 단어 수 / 질문 총 단어 수**로 비율을 계산한 후 셋째자리 까지 반올림하여 나타내었습니다.
0.0이 있다는게 눈에 띄어 0.0은 지문이 어떻게 나타나는지 확인해보았습니다.

---

### 형태소 분석이 잘못된 경우 

`도연주와 백승희는 무슨 사이로 알려졌나?` `정답: 친구`
> 이내창(李來昌, 1962년 ~ 1989년 8월 15일)은 의문사한 대한민국의 민주화 운동가이다.\n\n중동고등학교를 졸업하고 군복무를 마친 뒤 1986년 중앙대학교 안성캠퍼스 조소학과에 약간 늦은 나이에 입학했다. 이후 이내창은 판화 동아리를 창립하는 등 민족 미술 운동에 관심했고 학생 운동에 뛰어들었다.\n\n중앙대학교 미술대학 4학년에 올라가 안성캠퍼스 총학생회장을 지내던 1989년 여름, 거문도의 유림 해수욕장에서 물에 빠진 시신으로 발견되었다. 시신이 발견된 날짜는 여름 방학 중이던 8월 15일로, 총학생회장인 이내창이 주도하기로 되어 있던 교내 8·15 기념식을 앞두고 8월 14일 학교에서 나가는 모습이 목격된 뒤 하룻만이었다.\n\n이 사건은 당시 노태우 정부에서 단순 실족 사건 또는 자살 사건인 것으로 결론 지어졌으나 학생 운동 지도자인 이내창이 아무런 연고가 없는 거문도에서 목격자도 없이 사망했다는 정황에 대해서 많은 사람이 의구심을 품었다. 특히 이내창이 거문도로 가던 길에는 정체 불명의 여자가 동행했다는 증언이 나왔고 이 여자가 안전기획부의 직원이었다는 의혹도 제기되었다.\n\n2002년 대한민국의 대통령 소속 의문사진상규명위원회가 이 사건에 대한 중간 발표를 통하여 1989년 당시의 수사 결과와는 달리 이내창의 거문도행에 동행한 여자 **도연주**의 신분이 안기부 소속 직원이라는 사실이 확인되었고, 이 여자의 친구로 알려진 현직 군인 **백승희**를 포함한 다수 남자가 이내창의 사망시점에 거문도에 머물고 있었다고 발표했다. 이러한 발표는 이내창의 변사체가 발견된 이래 오랫동안 제기되었던 타살 의혹 또는 정보 기관 개입설을 뒷받침하는 것이었으나, 국가정보원이 자료 제출을 거부한 탓에 2004년 진상 규명이 더는 불가능하다고 결정됐다. \n\n유해는 경기도 이천 ‘민주화운동기념공원’에 안장되어 있다.  
~(여담이지만 스토리가 좀 무섭네요..)~

QA 형태소: ('도연', 'NNG'), ('주', 'NNG'), ('백승희', 'NNP'), ('사이', 'NNG')
CT 형태소: ('도', 'JX'), ('연주', 'NNG'), ('백', 'NR'), ('승희', 'NNG')

일단 위와 같이 직접적인 단서는 드러나지만, 형태소 분석에서의 차이 때문에 0.0으로 드러나는 지문이 있었습니다.
이런 현상은 주로 **고유명사가 많이 있을 때** 나타납니다. 고유명사에 대한 `mecab`의 형태소 분석이 좀 다르게 나타나는 것 같습니다. 

`아게실라오스의 아버지는 누구인가?` `정답: 아르키다모스 3세`
> 아기스 3세는 선왕 아르키다모스 3세의 아들이며, 후대의 왕 에우다미다스 1세의 동생이다. 그는 카이로네이아 전투가 있던 날에 왕위에 올랐다.\n\n기원전 333년 그는 에게 해에서 페르시아 제국 아케메네스 왕조 지휘관 파르나바조스, 아우토프라다테스와 회담을 갖고 마케도니아 왕국의 지배에 대항하여 스파르타의 반란을 일으키면 원조를 받기로 했다. 같은 해 〈이수스 전투〉 이후 아기스는 계획을 실행에 옮겼다. 우선 동생 **아게실라오스**를 크레타로 보내 기원전 331년에 스파르타를 비롯한 대 마케도니아 동맹에 참여했다 그리스 여러 도시 국가들은 마케도니아에 대한 트라키아의 반란을 틈타 대 마케도니아 전쟁을 선언했다.(그리스-마케도니아 전쟁). 그러나 그리스 도시 국가들이 굳건하게 뭉친 것은 아니어서, 아테나이 등이 불참했다. \n\n아기스는 스파르타 군과 이수스 전투에서 페르시아와 싸운 그리스인 용병 8000명, 그리고 동맹군을 더해 보병 20,000명, 기병 2,000기를 밑돌지 않는 병력을 모아 아기스 스스로 최고 사령관이 되었다. 그는 코라고스 휘하의 마케도니아 군을 펠로폰네소스에서 물리치고 결정적인 승리를 거두었다.\n\n다른 동맹군(엘리스, 아카이아, 아르카디아)의 합류로 아기스는 메갈로폴리스를 포위했다. 반면 비운의 알렉산더 3세로부터 그리스를 맡았던 마케도니아 장군 안티파트로스는 트라키아에서 반란을 정리하고, 즉시 40,000명 이상의 대군을 이끌고 메갈로폴리스를 구원하러 왔다. 그리고 양군은 〈가우가멜라 전투〉가 벌어진 것과 같은 시기에 회전을 치뤘다. (메갈로폴리스 전투) 격전이 계속되었지만, 마케도니아 군의 병력수에 밀린 아기스 군이 패배를 당했다. 아기스는 부상을 당했으면서도 계속 싸우다가 전사했다. 이 패배가 결정적이 되어 스파르타가 마케도니아를 상대로 일으킨 반란은 스파르타의 패배라는 결과로 끝났다.\n\n아기스는 자식을 남기지 않았기 때문에, 동생 에우다미다스가 다음 왕위를 계승했다.

위 지문도 마찬가지입니다.

QA 형태소: ('아', 'IC'), ('게실', 'NNG'), ('라오스', 'NNP'), ('아버지', 'NNG'), ('누구', 'NP')
CT 형태소: ('아', 'VV'), ('게', 'EC'), ('실라', 'NNP'), ('오스', 'NNP')

사실 고유명사 외에 다른 것에 대하여서도 형태소 분석이 조금 어긋나면 0.0의 ratio가 나타날 때가 있는 것 같습니다.
하지만 이건 MRC에 문제가 생길 것 같다기보다는 그냥 당장의 형태소 분석 문제라서 실제 MRC 모델 성능에도 유의미한 EDA가 될지는 모르겠습니다. 

---

### 문제가 어려운 경우

`민간인을 상대로 무차별 공격을 벌인 군대는?` `정답: 공화파 민병대`
> 스페인어로 '토레 (torre)'는 탑을 뜻하며, '온' (ón)은 엄청난 크기나 높이를 강조할 때 흔히 붙이는 접미사다. 따라서 '토레혼 (torrejón)'이라는 말은 '거대한 탑'이라고 해석해볼 수 있다. 토레혼데아르도스라는 지명이 언제부터 유래된 것인지는 명확히 밝혀진 바가 없으나 알칼라데에나레스에 성벽이 지어졌던 시기와 연관지어 본다면 대략 12세기 경으로 거슬러 올라갈 수 있다. \n\n1843년 에스파르테로 왕자에게 반기를 들고 난이 일어나면서, 라몬 나르바에스 장군과 안토니오 세오아네 상원의원이 이곳에서 짧은 전투를 벌이기도 했다. \n\n스페인 내전 초반에는 토레혼과 파라쿠에요스델하라마 사이에 있는 들판에서 **공화파 민병대가 프랑코파 군인들과 그를 지지하는 시민들(로 추정)을 사살하는 사건이 벌어졌는데 이를 파라쿠에요스 대학살이라고 부른다.**\n\n토레혼데아르도스에서 태어난 유명인으로는 옛날 토론토 랩터스에서 포워드로 뛰었던 농구선수 호르게 가르바호사, 레알 마드리드 FC 미드필더 구티, 오리건주지사 케이트 브라운, 그리고 프로레슬러 글렌 제이컵스 (링네임으로 케인)이 있다. 브라운과 제이컵스는 아버지가 미 공군 출신으로 이곳 기지에서 복무했었기에 토레혼에서 태어난 것이다.

위와 같이 정말 직접적으로 단어가 드러나지 않는 경우도 존재합니다.
'민간인' -> '시민들', '무차별 공격' -> '사살', '대학살'로 대응됩니다.

`역사상 가장 오랫동안 이용된 용광로는?` `정답: 와카야마 제4고로` 
> 주요 사업은 철강산업으로 강관, 박판, 후판, 건축 자재, 철도 차량부품, 티타늄, 조강 등을 생산하는(조강 생산량은 연간 1000만톤) 업체였다. 이 중에서도 ‘파이프의 주금’이라고 말하는 것과 같이 심리스 파이프라는 원유 발굴용 강관은 세계적으로도 높은 지위를 확보하고 있었다. 그러나 심리스 파이프 가격은 유가와 연동되기 때문에, 1990년대의 유가 침체기에는 심리스 파이프도 적자를 내고 있었다. 이것은 주금 경영의 발목을 잡고 있었지만, 2000년 이후 원유 가격의 상승으로 수익이 개선되었다.\n주력 제철소는 가시마 제철소와 와카야마 제철소이다. 가시마 제철소는 일본에서는 비교적 새로운 제철소에서 생산 효율이 뛰어났다. 2004년에는 가시마 제철소 내 대형의 새 고로를 건설했고, 비용 절감을 추진했다. 반면 와카야마 제철소는 오래되었기 때문에 생산 효율이 떨어져 있었다. 따라서 열간압연밀 라인의 중단과 상위 공정(제선 · 제강 라인)은 대만 · 중국강 철과의 합작 회사로 분리시키는 등 대규모 구조조정을 단행했다. 현재는 완벽한 파이프 생산 거점으로서 중요한 역할을 하고 있으며, 하이난시 하이난 강관 공장을 포함하여 새로운 설비 투자가 이루어졌다. **이 설비 투자를 통해 그 역할을 끝냈던 와카야마 제4고로는 1982년 2월 23일의 점화 이후 2009년 7월 11일 중단을 멈출 때까지, 27년 4개월 실행 가동일수를 기록하여 세계 최장 기록을 달성했다.**

마찬가지로 사용되는 단어가 다릅니다.
'용광로'라는 단어가 직접적으로 드러나지 않는다는 점도 좀 눈여겨볼만 한 것 같아요

`사후세계의 존재를 믿는 민족은?` `정답: 잉카인`
> 11월 7일, 스페인 군대는 아타우알파가 머물던 캠프를 공격하였고, 그 곳에서 수많은 황금, 은, 에메랄드 등을 찾아낸다. 스페인 사람들이 금과 보석을 매우 좋아한다는 것을 알게 된 아타우알파는, 만약 그들이 그를 풀어준다면 2달 안에 가로 6.7m, 세로 5.2m, 높이 2.4m에 달하는 방 하나를 가득 채울만한 금과, 이 양의 2배에 달하는 은을 주겠다고 제안한다. 보통 사람들은 아타우알파가 그의 자유를 위해 이런 제안을 했다고 알고 있지만, 대부분의 초기 역사 문헌들을 보면 아타우알파가 자유는커녕 목숨의 보전을 위해 이 제안을 할 수 밖에 없었다고 여겨진다. 대다수의 기록에는 스페인 군인들이 황금을 얻은 후에도 황제를 풀어주려는 생각을 아예 하지 않았기 때문이다.\n 몇 달 후, 잉카 대군의 기습을 두려워 한 스페인 군인들은, 아타우알파가 포로로 살려두기에는 너무 위험한 인물이라는 생각을 하게 된다. 피사로는 임시로 법정을 세우고, 아타우알파를 우상 숭배, 스페인에 대한 반란, 우아스카르 살해 등에 대한 죄목으로 유죄를 선고했다. 아타우알파는 화형당하는 벌을 받게 되었는데, **당시의 잉카인들은 만약 시체가 사라지면 결코 내세에 갈 수 없다고 믿었기에 아타우알파는 경악했다.** 이때, 발베데레 수사는 그에게 만약 그가 가톨릭으로 개종한다면, 화형은 아닐지라도 교살로 형을 낮추어주겠다고 제안했다. 아타우알파는 이 제안을 받아들였고, 프란치스코 아타우알파라는 이름으로 세례를 받았다.\n\n그가 죽던 날 아침, 스페인인들은 그에게 그가 어디에서 태어났는지를 심문했고, 아타우알파는 그가 키토 왕국령에서 태어났다고 말했다. 그의 나이에 대해서 물었을 때에는, "우리는 너희 서양인들이 하는 것처럼 시간을 세지 않는다. 하지만 나는 내가 태어난 이래 31번의 수확을 경험했다."라고 말했다.\n\n그의 요구에 따라, 그는 1533년 7월 26일 교살로 사형당했다. 하지만 시체가 사라지기를 원치 않았던 아타우알파의 바람과는 달리, 그의 옷과 피부 일부분은 불로 태웠고, 유해는 가톨릭 식으로 장례 절차를 밟게 되었다. 황제의 자리는 그의 형제인 투팍 우알파에 의해 계승되었다.

'사후세계' -> '내세에 갈 수 없다고 믿었기에' 
비슷한 추론 문제입니다. 세 개 중에선 난이도가 가장 있는 것 같은데요..? 

---

### 사람도 틀릴만한 문제..? 

`간부 양성 목적으로 설립된 시설의 이름은?` `정답: 황푸 군사 학교`
> 일본의 항복 후, 푸쭤이는 쑤이위안성, 차하르성과 러허성에서 공산군들을 싸우면서 돌격되었다. 충칭과 정치 자문 회의에서 강화 협상의 실패 후에 국민당과 공산당은 둘다 1946년 6월 전면적인 내전을 시작하였다. 1947년 중순에 국민당군의 공세는 실패하였고, 푸쭤이의 "군사적 20%, 정치적 30%와 경제적 50%"의 정책은 공산당의 권력 기지였던 북중국에서 공산군들을 해치울 수 없었다.\n\n1947년 12월 베이핑에서 북중국 마적 진압의 총사령부의 최고 사령관으로서 황푸 군사 학교를 졸업하지 않은 지방적 지도자인 푸쭤이를 임명하였다. 푸쭤이는 옌시산의 산서성을 제외한 북중국 국민당의 사실상 정치적 지도자가 되었다. 1948년 중국공산당의 지하 당원들은 푸쭤이의 총사령부와 가족 안에서 연합 전선 활동들을 수행하였다. 특히 그의 딸 푸둥쥐는 부친에 일하는 데 중국공산당에 의하여 지정되었다. 11월에 시작된 베이핑-톈진 전투에서 자신의 군대의 대부분의 절멸 후에 푸쭤이는 12월 후순 중국공산당에게 항복하기로 결정하였다.

솔직히 때려맞출순 있어도 간부 양성 목적으로 설립되었다는 직접적인 단서가 드러나있지 않습니다. 머신이 기계독해를 어떤식으로 할지는 모르겠지만 좀 당황스러운 문제에요.

---

0.0이 뜬 것만 지문을 대충 다 살펴봤는데 비율로 따지면 1번 케이스가 80%이상 되는 것 같고, 2번 케이스는 15% 정도?, 3번 케이스는 정말 가끔 등장합니다.
앞서 언급했듯이 형태소 분석의 문제가 MRC 성능과 직접적 연관이 있을지는 잘 모르겠습니다만.. 아무튼 단어 안겹치는 경우도 꽤나 존재하는 것 같습니다.

제 생각에는 아래와 같은 추가적인 분석을 한다면 더 좋을 것 같습니다.
- 질문에 slicing window를 적용하여 **연속되는 단어 리스트**가 지문에서도 드러나는지 확인
- window를 적용한다면 그 수치는 얼마정도로 해야할지

또한 지금처럼 임의로 몇 개 형태소들만 뽑아내서 분석하는게 좋은 결과를 내는걸까? 라는 의문도 남습니다.

**Comment by sooyounlee** [comment]
저 '사람도 틀릴만한 문제'는 ODQA 질문으로는 정말 적합하지가 않네요 ㅎㅎ 가능한 답이 엄청 많을 것 같아요! 고유 명사가 쪼개지는 경우에는 vocab에 추가해주는게 좋으려나요... 생각해 볼 문제네요!
