### ISSUE TITLE
[QA/REVIEW] 현재(05.11)까지 최고 성능 MRC 모델의 prediction 분석 EDA

### ISSUE THREAD

**Issue by SeongIkKim** [VumBleBot/Group-Activity#58]
##  📸  코드

모델 prediction은 건모님이 넘겨주신 koelectra 베이스, korquad 데이터셋 샘플링하여 추가한 모델 기준입니다.
EM 60%를 기록했던 모델입니다.

[prediction EDA](https://github.com/VumBleBot/Group-Activity/blob/main/documents/EDA/prediction_eda.ipynb)

틀린 답을 나눠보자면 다음과 같이 나눌 수 있습니다. 자세한 확인은 github에서 보시길 바랍니다.

### 1. 유사관계 : 형식은 맞지만 디테일이 다른 경우
    - pred: 1967년 8월 16일 answer: 1967년 11월 15일 mispredict: 86 => 날짜형식은 맞추었지만 정확한 숫자가 틀림
    - pred: 이이노야 성 answer: 미타케성 mispredict: 이이노야 => 성이라는 형식은 맞추었지만 정확한 이름이 틀림
    - pred:이치키 마츠히로  answer: 신도 케이  mispredict:이치키 마츠히로
       
### 2. 포함관계 : 정답 어구의 일부분만을 예측했거나, 정답 어구를 포함한 어구를 예측한 경우
    1. 정답어구의 일부분만을 예측한 경우
        - pred: 4순위 answer: 전체 4순위 mispredict
        - _pred: 베게티우스 answer: 작가 베게티우스 mispredict:_
            - 이 경우에는 과연 틀렸다고 봐야하는 걸까요? 의문점이 남습니다.
        - pred: 망치 answer: 쇠망치 mispredict:
        - pred: 걸프 카르텔 answer: 걸프 카르텔(카르텔 델 골포: Cartel del golfo) mispredict:
        - pred: 도로스 answer: 대형 항공 모함 도로스 mispredict:
    2. 정답 어구를 포함하여 너무 많은 부분을 예측으로 내놓은 경우 --> 이 경우는 에폭을 늘려 학습을 더 했어야 했던 것일까요?
        - pred: 나말여초 불상 answer: 나말여초 mispredict:  불상
        - pred: 1945년과 1960년대 후반 answer: 1945년 mispredict: 과 1960년대 후반
        - _pred: 젊은 근위대 answer: ＜젊은 근위대＞ mispredict:_ => 아마도 이러한 경우는 LB상에서는 정답처리 될 듯합니다.
        - pred: 탄광 환경 문제 answer: 탄광 mispredict:  환경 문제
        - pred: 별도로 분리된 투표를 했다. 각 부족마다 다수결 득표 answer: 다수결 mispredict: 별도로 분리된 투표를 했다. 각 부족마다 다수결 득표

### 3. _언어는 이해했으나 맥락을 파악못한 경우(주목할만한 경우)_
    - **동일한 글자매칭이 없는 경우에도 의미상 비슷한 종류의 단어를 캐치한 사례가 있었습니다.(언어 학습이 어느정도 잘 되었다는 것을 의미)**
    - pred: 수원 answer: 울산 mispredict: 수원
    - pred: 우익진영 answer: 공산당 mispredict: 우익진영
    - pred: 범퍼 answer: 트렁크 mispredict: 범퍼
    - pred:안평군 answer: 제 양왕  mispredict:안평군
    - pred:대부업 answer: '사채회사' mispredict:대부업

### 4. 아예 이해를 하지 못한 경우 -> 정답의 근거가 되는 context를 살펴보고 추가적인 EDA가 더 필요합니다.
    - pred:비록  answer: 가루아  mispredict:비록
    - pred:때론  answer: 사춘기에서 흔히 볼 수 있는 정서적 불안정성 mispredict:때론
    - pred:오로지  answer: 모든 관직을 거친 대과 급제자 mispredict:오로지
    
### 5. 서술형
    - pred:“어떤 경우에도 행할 수” answer: 본국 의회가 식민지에 대한 입법을 “어떤 경우에도 행할 수” 있도록 하였다  => 대부분 단답형의 example로 학습한 BERT가 맞추기 어려운 서술형의 답
    - pred:상급자 수준의  answer: 깃털 셔틀콕의 타구감을 선호하고, 또한 플라스틱보다 깃털 셔틀콕이 정교한 컨트롤을 하기에 보다 더 적합하기 때문이다 mispredict:상급자 수준의

github에서는 color 라이브러리 적용이 안되어 시각적으로 보기가 불편해서 이미지를 남깁니다.

![Screen Shot 2021-05-11 at 8 44 53 PM](https://user-images.githubusercontent.com/26772420/117810059-e82dfb00-b299-11eb-9b15-e3b93e460a89.png)
![Screen Shot 2021-05-11 at 8 45 15 PM](https://user-images.githubusercontent.com/26772420/117810076-ec5a1880-b299-11eb-810c-4a769293ba36.png)
![Screen Shot 2021-05-11 at 8 45 22 PM](https://user-images.githubusercontent.com/26772420/117810090-f1b76300-b299-11eb-9ffc-92de054d160e.png)

---

## 🤔  궁금한 점

- LB 스코어로 들어갔을때 한자 동의어 등이 표현된 경우 EM으로 쳐줄까?
- 포함관계의 오답을 어떻게 처리할 수 있을까?
- 서술형의 답을 어떻게 캐치할 수 있을까?

시각화와 더 나은 전처리, EDA를 위해서 여러분들의 의견이 많이 필요합니다!
생각나는 아이디어 있으면 다 던져주세요!! 🤝

---

## 📚  레퍼런스 첨부

- 의문 해결에 도움을 주는 참고 문헌이 있다면 기록해주세요!
- 책, 블로그, 유튜브, 논문 등

**Comment by sooyounlee** [comment]
너무 재밌게 봤어요! github에서 먼저 확인해서 색이 들어간지 몰랐는데 저렇게 색 구분을 해서 보니 훨씬 눈에 잘 들어오네요~
서술형 문답이 있는 줄 몰랐는데, 정말 맞추기가 쉽지 않아보여요. KLUE에도 왠지 적게 포함되어있을 것 같은데 어떻게 데이터를 늘릴 수 있을지/ 아니면 class imbalance를 모델에서 해결하는 방향으로 가야하는건지 고민을 해봐야겠네요!
2번 같은 경우는 진짜 정답을 많이 맞춘 느낌인데..ㅎㅎㅎ 이게 또 주최측에서 정해준 정답만을 맞춰야 하는 한계점이 있는 것 같네요!? 사실 한자가 포함되든 되지 않든 정답 인정은 되어야할 것 같기도 하구요...
생각해볼 거리가 많네요! 좋은 EDA 감사합니다 😸
