### ISSUE TITLE
[QA/REVIEW] 후처리 : POS 태깅을 이용한 조사 제거, 정답이 안될법한 것 제거

### ISSUE THREAD

**Issue by SeongIkKim** [VumBleBot/Group-Activity#59]
##  📸  코드

mecab을 이용한 형태소분석으로 nbest prediction의 순서를 조정해 정답이 아닌 것의 순서를 뒤로 보내어 best prediction을 올리려고 했습니다.

## 기존 코드
![Screen Shot 2021-05-14 at 1 10 15 AM](https://user-images.githubusercontent.com/26772420/118153705-2588b900-b451-11eb-83e8-c8393888d30b.png)

**55.42%**

## 명사가 들어가지 않은 예측을 낮은 순위로 변경
![Screen Shot 2021-05-14 at 1 10 44 AM](https://user-images.githubusercontent.com/26772420/118153762-36d1c580-b451-11eb-9d13-97db45e54ada.png)

**55.00%**

## 마지막 단어가 조사인 예측을 낮은 순위로 변경
![Screen Shot 2021-05-14 at 1 14 07 AM](https://user-images.githubusercontent.com/26772420/118154168-b069b380-b451-11eb-9927-9040a526a2f6.png)

**54.58%**

## 두가지 모두 적용
![Screen Shot 2021-05-14 at 1 15 08 AM](https://user-images.githubusercontent.com/26772420/118154289-d42cf980-b451-11eb-9bf3-e475ebc64148.png)

**54.17%**

모두 오히려 역효과가 났습니다.

---

## 🤔  궁금한 점

- mecab의 형태소 분석 성능이 생각보다 좋지 않습니다.
  - 그래서 kiwi등의 다른 형태소 분석기도 사용해봤는데 오히려 맞춘 부분에서 성능이 떨어졌습니다(...)
- 설령 형태소 분석을 잘한다고 하더라도 일반적으로 best prediction이 터무니없는 답이나 조사가 들어간 답인 경우가 거의 없어서 효과가 별로 없었습니다.

---

## 📚  레퍼런스 첨부

- 의문 해결에 도움을 주는 참고 문헌이 있다면 기록해주세요!
- 책, 블로그, 유튜브, 논문 등

**Comment by sooyounlee** [comment]
이거 Mecab을 언제 적용하셨나요? Mecab으로 형태소 판별하려면 온전한 문장을 넣어줘야한다고 하더라구요! 혹시 prediction 이후의 어구를 통과시키신거라면 형태소 판별이 잘 안되었을 수도 있을 것 같습니다.

**Comment by SeongIkKim** [comment]
@sooyounlee Prediction 이후의 어구를 넣었습니다! 그래서 판별이 잘 안되었던 걸 수도 있겠네요. 다만 prediction 하기 전의 문장을 넣어주기에는 이미 logit값으로 자른 뒤의 offset maching을 넘겨받아서.. 다시 원문 context에서 text를 복원하여 해당 문장을 집어넣고 조사를 제거하는 방법도 불가능하진 않을것 같은데 연산이 너무 커져서 리소스를 너무 많이 잡아먹지 않을까 합니다 ㅠㅠ
