### ISSUE TITLE
[TODO] 보면 좋을 것 같은 논문 리스트

### ISSUE THREAD

**Issue by sooyounlee** [VumBleBot/Group-Activity#60]
- SPARTA: Efficient Open-Domain Question Answering via Sparse Transformer Matching Retrieval, 28 Sep 2020, Tiancheng Zhao, Xiaopeng Lu, Kyusong Lee [논문 링크](https://arxiv.org/pdf/2009.13013v1.pdf)
    - ODQA task SQuAD1.1 dev SOTA 모델
    - Dense Retriever 혹은 Reader로 활용될 수 있는 논문

- Data Augmentation for BERT Fine-Tuning in Open-Domain Question Answering, 14 Apr 2019, Wei Yang, Yuqing Xie, Luchen Tan, Kun Xiong, Ming Li, Jimmy Lin [논문 링크](https://arxiv.org/pdf/1904.06652v1.pdf)
  - Dense retriever training 시 data augmentation 후 어떻게 training하는 것이 효과적인지 review한 논문

(추가 예정)

**Comment by SeongIkKim** [comment]
감사합니다! 주말간에 시간을 많이 못낼것 같긴한데 일단 논문 틈틈이 보고있겠습니다 ㅠㅠ
